name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.0+99

# The following defines the version and build number for your application.
environment:
  sdk: ^3.10.7

# The following section is specific to Flutter packages.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  sqflite_sqlcipher: ^3.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  web_socket_channel: ^3.0.3
  cryptography: ^2.7.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.3
  flutter_markdown_plus: ^1.0.7
  hugeicons: ^1.1.5
  crypto: ^3.0.0
  flutter_webrtc:
    path: vendor/flutter_webrtc
  permission_handler: ^11.3.1
  wakelock_plus: ^1.2.8

# The following section is specific to Flutter packages.
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting and code generation tools
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# The following section is specific to Flutter packages.
flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png
  remove_alpha_ios: true
